In [16]:
import pandas as pd
import numpy as np

In [77]:
data=pd.read_excel('customer.xlsx')
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [78]:
data.drop_duplicates()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [79]:
df=data.drop(columns='Not_Useful_Column')

In [80]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [81]:
df["Phone_Number"]=df["Phone_Number"].str.replace('N/a','0')

In [82]:
df["Phone_Number"]=df["Phone_Number"].fillna(0)

In [83]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,0,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,0,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,0,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,0,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,0,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,0,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,0,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [84]:
df[["street","state","zip"]] = df["Address"].str.split(',',n=2,expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,/White,0,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,0,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,0,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,0,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,0,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,0,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,0,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [85]:
df1=df.drop(columns="Address")
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,/White,0,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,0,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,0,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,0,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,0,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,0,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,0,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,Yes,N,910 Tatooine Road,Tatooine,None

In [86]:
df1["Paying Customer"]=df1["Paying Customer"].str.replace("N/a","0")
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,/White,0,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,0,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,0,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,0,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,0,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,0,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,0,0,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,Yes,N,910 Tatooine Road,Tatooine,None

In [87]:
df1["Paying Customer"]=df1["Paying Customer"].apply(lambda x:"Yes" if x=='Y' else x)

In [88]:
df1["Paying Customer"]=df1["Paying Customer"].apply(lambda x:"No" if x=='N' else x)

In [89]:
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,/White,0,No,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,Yes,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,0,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,No,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,0,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,0,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,0,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,0,Yes,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,0,0,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,Yes,N,910 Tatooine Road,Tatooine,None

In [90]:
df1["Do_Not_Contact"]=df1["Do_Not_Contact"].apply(lambda x:"Yes" if x=='Y' else x)

In [91]:
df1["Do_Not_Contact"]=df1["Do_Not_Contact"].apply(lambda x:"No" if x=='N' else x)
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,/White,0,No,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Yes,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,Yes,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,0,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,No,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,0,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,0,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,0,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,0,Yes,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,0,0,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,Yes,No,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,Yes,No,910 Tatooine Road,Tatooine,None

In [92]:
df1["Do_Not_Contact	"]=df1["Do_Not_Contact"].str.replace("NaN","0")
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip,Do_Not_Contact\t
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None,No
1,1002,Abed,Nadir,123/643/9775,No,Yes,93 West Main Street,None,None,Yes
2,1003,Walter,/White,0,No,NaN,298 Drugs Driveway,None,None,NaN
3,1004,Dwight,Schrute,123-543-2345,Yes,Yes,980 Paper Avenue,Pennsylvania,18503,Yes
4,1005,Jon,Snow,876|678|3469,Yes,No,123 Dragons Road,None,None,No
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None,Yes
6,1007,Jeff,Winger,0,No,No,1209 South Street,None,None,No
7,1008,Sherlock,Holmes,876|678|3469,No,No,98 Clue Drive,None,None,No
8,1009,Gandalf,NaN,0,Yes,NaN,123 Middle Earth,None,None,NaN
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None,No
10,1011,Samwise,Gamgee,0,Yes,No,612 Shire Lane,Shire,None,No
11,1012,Harry,...Potter,0,Yes,NaN,2394 Hogwarts Avenue,None,None,NaN
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street,None,None,No
13,1014,Leslie,Knope,876|678|3469,Yes,No,343 City Parkway,None,None,No
14,1015,Toby,Flenderson_,304-762-2467,No,No,214 HR Avenue,None,None,No
15,1016,Ron,Weasley,123-545-5421,No,No,2395 Hogwarts Avenue,None,None,No
16,1017,Michael,Scott,123/643/9775,Yes,No,121 Paper Avenue,Pennsylvania,None,No
17,1018,Clark,Kent,0,Yes,NaN,3498 Super Lane,None,None,NaN
18,1019,Creed,Braton,0,0,Yes,N/a,None,None,Yes
19,1020,Anakin,Skywalker,876|678|3469,Yes,No,910 Tatooine Road,Tatooine,None,No
20,1020,Anakin,Skywalker,876|678|3469,Yes,No,910 Tatooine Road,Tatooine,None,No

In [93]:
df1["Do_Not_Contact"]=df1["Do_Not_Contact"].fillna(0)
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip,Do_Not_Contact\t
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None,No
1,1002,Abed,Nadir,123/643/9775,No,Yes,93 West Main Street,None,None,Yes
2,1003,Walter,/White,0,No,0,298 Drugs Driveway,None,None,NaN
3,1004,Dwight,Schrute,123-543-2345,Yes,Yes,980 Paper Avenue,Pennsylvania,18503,Yes
4,1005,Jon,Snow,876|678|3469,Yes,No,123 Dragons Road,None,None,No
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None,Yes
6,1007,Jeff,Winger,0,No,No,1209 South Street,None,None,No
7,1008,Sherlock,Holmes,876|678|3469,No,No,98 Clue Drive,None,None,No
8,1009,Gandalf,NaN,0,Yes,0,123 Middle Earth,None,None,NaN
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None,No
10,1011,Samwise,Gamgee,0,Yes,No,612 Shire Lane,Shire,None,No
11,1012,Harry,...Potter,0,Yes,0,2394 Hogwarts Avenue,None,None,NaN
12,1013,Don,Draper,123-543-2345,Yes,No,2039 Main Street,None,None,No
13,1014,Leslie,Knope,876|678|3469,Yes,No,343 City Parkway,None,None,No
14,1015,Toby,Flenderson_,304-762-2467,No,No,214 HR Avenue,None,None,No
15,1016,Ron,Weasley,123-545-5421,No,No,2395 Hogwarts Avenue,None,None,No
16,1017,Michael,Scott,123/643/9775,Yes,No,121 Paper Avenue,Pennsylvania,None,No
17,1018,Clark,Kent,0,Yes,0,3498 Super Lane,None,None,NaN
18,1019,Creed,Braton,0,0,Yes,N/a,None,None,Yes
19,1020,Anakin,Skywalker,876|678|3469,Yes,No,910 Tatooine Road,Tatooine,None,No
20,1020,Anakin,Skywalker,876|678|3469,Yes,No,910 Tatooine Road,Tatooine,None,No